
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("ea796f19-b181-4e2f-a6b9-0ecbec2f9d05")>

#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("ilockboxModel", "FK_Batchmodetbl_Wrksrctbl1", "Wrksrctbl", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Wrksrctbl), "Batchmodetbl", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Batchmodetbl))>
<Assembly: EdmRelationshipAttribute("ilockboxModel", "FK_Batchtbl_Wrksrctbl", "Wrksrctbl", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Wrksrctbl), "Batchtbl", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Batchtbl))>
<Assembly: EdmRelationshipAttribute("ilockboxModel", "FK_DetailTbl_Batchtbl1", "Batchtbl", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Batchtbl), "DetailTbl", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DetailTbl))>
<Assembly: EdmRelationshipAttribute("ilockboxModel", "FK_BatchValue_Wrksrctbl", "Wrksrctbl", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Wrksrctbl), "BatchValue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(BatchValue))>
<Assembly: EdmRelationshipAttribute("ilockboxModel", "FK_ImgTbl_Wrksrctbl", "Wrksrctbl", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Wrksrctbl), "ImgTbl", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ImgTbl))>
<Assembly: EdmRelationshipAttribute("ilockboxModel", "FK_ItemSelectTbl_Wrksrctbl", "Wrksrctbl", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Wrksrctbl), "ItemSelectTbl", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ItemSelectTbl))>
#End Region

#Region "Contexts"
''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class ilockboxEntities 
    Inherits ObjectContext

    #Region "Constructors"
    ''' <summary>
    ''' Initializes a new ilockboxEntities object using the connection string found in the 'ilockboxEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New() 
        MyBase.New("name=ilockboxEntities", "ilockboxEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new ilockboxEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "ilockboxEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new ilockboxEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "ilockboxEntities")
        OnContextCreated()
    End Sub
    #End Region
    
    #Region "Partial Methods"
    Partial Private Sub OnContextCreated()
    End Sub
    #End Region
    
    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Batchmodetbl() As ObjectSet(Of Batchmodetbl)
        Get
            If (_Batchmodetbl Is Nothing) Then
                _Batchmodetbl = MyBase.CreateObjectSet(Of Batchmodetbl)("Batchmodetbl")
            End If
            Return _Batchmodetbl
        End Get
    End Property
    
    Private _Batchmodetbl As ObjectSet(Of Batchmodetbl)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Batchtbl() As ObjectSet(Of Batchtbl)
        Get
            If (_Batchtbl Is Nothing) Then
                _Batchtbl = MyBase.CreateObjectSet(Of Batchtbl)("Batchtbl")
            End If
            Return _Batchtbl
        End Get
    End Property
    
    Private _Batchtbl As ObjectSet(Of Batchtbl)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property BatchValue() As ObjectSet(Of BatchValue)
        Get
            If (_BatchValue Is Nothing) Then
                _BatchValue = MyBase.CreateObjectSet(Of BatchValue)("BatchValue")
            End If
            Return _BatchValue
        End Get
    End Property
    
    Private _BatchValue As ObjectSet(Of BatchValue)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property DetailTbl() As ObjectSet(Of DetailTbl)
        Get
            If (_DetailTbl Is Nothing) Then
                _DetailTbl = MyBase.CreateObjectSet(Of DetailTbl)("DetailTbl")
            End If
            Return _DetailTbl
        End Get
    End Property
    
    Private _DetailTbl As ObjectSet(Of DetailTbl)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ImgTbl() As ObjectSet(Of ImgTbl)
        Get
            If (_ImgTbl Is Nothing) Then
                _ImgTbl = MyBase.CreateObjectSet(Of ImgTbl)("ImgTbl")
            End If
            Return _ImgTbl
        End Get
    End Property
    
    Private _ImgTbl As ObjectSet(Of ImgTbl)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ItemSelectTbl() As ObjectSet(Of ItemSelectTbl)
        Get
            If (_ItemSelectTbl Is Nothing) Then
                _ItemSelectTbl = MyBase.CreateObjectSet(Of ItemSelectTbl)("ItemSelectTbl")
            End If
            Return _ItemSelectTbl
        End Get
    End Property
    
    Private _ItemSelectTbl As ObjectSet(Of ItemSelectTbl)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Wrksrctbl() As ObjectSet(Of Wrksrctbl)
        Get
            If (_Wrksrctbl Is Nothing) Then
                _Wrksrctbl = MyBase.CreateObjectSet(Of Wrksrctbl)("Wrksrctbl")
            End If
            Return _Wrksrctbl
        End Get
    End Property
    
    Private _Wrksrctbl As ObjectSet(Of Wrksrctbl)
    #End Region
    #Region "AddTo Methods"
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the Batchmodetbl EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToBatchmodetbl(ByVal batchmodetbl As Batchmodetbl)
        MyBase.AddObject("Batchmodetbl", batchmodetbl)
    End Sub
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the Batchtbl EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToBatchtbl(ByVal batchtbl As Batchtbl)
        MyBase.AddObject("Batchtbl", batchtbl)
    End Sub
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the BatchValue EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToBatchValue(ByVal batchValue As BatchValue)
        MyBase.AddObject("BatchValue", batchValue)
    End Sub
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the DetailTbl EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDetailTbl(ByVal detailTbl As DetailTbl)
        MyBase.AddObject("DetailTbl", detailTbl)
    End Sub
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the ImgTbl EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToImgTbl(ByVal imgTbl As ImgTbl)
        MyBase.AddObject("ImgTbl", imgTbl)
    End Sub
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the ItemSelectTbl EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToItemSelectTbl(ByVal itemSelectTbl As ItemSelectTbl)
        MyBase.AddObject("ItemSelectTbl", itemSelectTbl)
    End Sub
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the Wrksrctbl EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToWrksrctbl(ByVal wrksrctbl As Wrksrctbl)
        MyBase.AddObject("Wrksrctbl", wrksrctbl)
    End Sub
    #End Region
End Class

#End Region
#Region "Entities"
''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ilockboxModel", Name:="Batchmodetbl")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Batchmodetbl 
    Inherits EntityObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new Batchmodetbl object.
    ''' </summary>
    ''' <param name="workSource">Initial value of the WorkSource property.</param>
    ''' <param name="subSet">Initial value of the SubSet property.</param>
    ''' <param name="batchMode">Initial value of the BatchMode property.</param>
    Public Shared Function CreateBatchmodetbl(workSource As Global.System.String, subSet As Global.System.Int16, batchMode As Global.System.Int16) As Batchmodetbl
        Dim batchmodetbl as Batchmodetbl = New Batchmodetbl
        batchmodetbl.WorkSource = workSource
            
        batchmodetbl.SubSet = subSet
            
        batchmodetbl.BatchMode = batchMode
            
        Return batchmodetbl
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property WorkSource() As Global.System.String
        Get
            Return _WorkSource
        End Get
        Set
            If (WorkSource <> value) Then
                OnWorkSourceChanging(value)
                ReportPropertyChanging("WorkSource")
                _WorkSource = StructuralObject.SetValidValue(value, False)
                ReportPropertyChanged("WorkSource")
                OnWorkSourceChanged()
            End If
        End Set
    End Property
    
    Private _WorkSource as Global.System.String
    Private Partial Sub OnWorkSourceChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnWorkSourceChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SubSet() As Global.System.Int16
        Get
            Return _SubSet
        End Get
        Set
            If (SubSet <> value) Then
                OnSubSetChanging(value)
                ReportPropertyChanging("SubSet")
                _SubSet = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SubSet")
                OnSubSetChanged()
            End If
        End Set
    End Property
    
    Private _SubSet as Global.System.Int16
    Private Partial Sub OnSubSetChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnSubSetChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BatchMode() As Global.System.Int16
        Get
            Return _BatchMode
        End Get
        Set
            If (BatchMode <> value) Then
                OnBatchModeChanging(value)
                ReportPropertyChanging("BatchMode")
                _BatchMode = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("BatchMode")
                OnBatchModeChanged()
            End If
        End Set
    End Property
    
    Private _BatchMode as Global.System.Int16
    Private Partial Sub OnBatchModeChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnBatchModeChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property
    
    Private _Name as Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnNameChanged()
    End Sub
    
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_Batchmodetbl_Wrksrctbl1", "Wrksrctbl")>
    Public Property Wrksrctbl() As Wrksrctbl
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_Batchmodetbl_Wrksrctbl1", "Wrksrctbl").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_Batchmodetbl_Wrksrctbl1", "Wrksrctbl").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property WrksrctblReference() As EntityReference(Of Wrksrctbl)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_Batchmodetbl_Wrksrctbl1", "Wrksrctbl")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_Batchmodetbl_Wrksrctbl1", "Wrksrctbl", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ilockboxModel", Name:="Batchtbl")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Batchtbl 
    Inherits EntityObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new Batchtbl object.
    ''' </summary>
    ''' <param name="processDt">Initial value of the ProcessDt property.</param>
    ''' <param name="workSource">Initial value of the WorkSource property.</param>
    ''' <param name="subSet">Initial value of the SubSet property.</param>
    ''' <param name="batchNumber">Initial value of the BatchNumber property.</param>
    Public Shared Function CreateBatchtbl(processDt As Global.System.DateTime, workSource As Global.System.String, subSet As Global.System.Int16, batchNumber As Global.System.String) As Batchtbl
        Dim batchtbl as Batchtbl = New Batchtbl
        batchtbl.ProcessDt = processDt
            
        batchtbl.WorkSource = workSource
            
        batchtbl.SubSet = subSet
            
        batchtbl.BatchNumber = batchNumber
            
        Return batchtbl
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProcessDt() As Global.System.DateTime
        Get
            Return _ProcessDt
        End Get
        Set
            If (ProcessDt <> value) Then
                OnProcessDtChanging(value)
                ReportPropertyChanging("ProcessDt")
                _ProcessDt = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ProcessDt")
                OnProcessDtChanged()
            End If
        End Set
    End Property
    
    Private _ProcessDt as Global.System.DateTime
    Private Partial Sub OnProcessDtChanging(value As Global.System.DateTime)
    End Sub
    
    Private Partial Sub OnProcessDtChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property WorkSource() As Global.System.String
        Get
            Return _WorkSource
        End Get
        Set
            If (WorkSource <> value) Then
                OnWorkSourceChanging(value)
                ReportPropertyChanging("WorkSource")
                _WorkSource = StructuralObject.SetValidValue(value, False)
                ReportPropertyChanged("WorkSource")
                OnWorkSourceChanged()
            End If
        End Set
    End Property
    
    Private _WorkSource as Global.System.String
    Private Partial Sub OnWorkSourceChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnWorkSourceChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SubSet() As Global.System.Int16
        Get
            Return _SubSet
        End Get
        Set
            If (SubSet <> value) Then
                OnSubSetChanging(value)
                ReportPropertyChanging("SubSet")
                _SubSet = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SubSet")
                OnSubSetChanged()
            End If
        End Set
    End Property
    
    Private _SubSet as Global.System.Int16
    Private Partial Sub OnSubSetChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnSubSetChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BatchNumber() As Global.System.String
        Get
            Return _BatchNumber
        End Get
        Set
            If (BatchNumber <> value) Then
                OnBatchNumberChanging(value)
                ReportPropertyChanging("BatchNumber")
                _BatchNumber = StructuralObject.SetValidValue(value, False)
                ReportPropertyChanged("BatchNumber")
                OnBatchNumberChanged()
            End If
        End Set
    End Property
    
    Private _BatchNumber as Global.System.String
    Private Partial Sub OnBatchNumberChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnBatchNumberChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Status() As Global.System.String
        Get
            Return _Status
        End Get
        Set
            OnStatusChanging(value)
            ReportPropertyChanging("Status")
            _Status = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Status")
            OnStatusChanged()
        End Set
    End Property
    
    Private _Status as Global.System.String
    Private Partial Sub OnStatusChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnStatusChanged()
    End Sub
    
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_Batchtbl_Wrksrctbl", "Wrksrctbl")>
    Public Property Wrksrctbl() As Wrksrctbl
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_Batchtbl_Wrksrctbl", "Wrksrctbl").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_Batchtbl_Wrksrctbl", "Wrksrctbl").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property WrksrctblReference() As EntityReference(Of Wrksrctbl)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_Batchtbl_Wrksrctbl", "Wrksrctbl")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_Batchtbl_Wrksrctbl", "Wrksrctbl", value)
            End If
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_DetailTbl_Batchtbl1", "DetailTbl")>
     Public Property DetailTbl() As EntityCollection(Of DetailTbl)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DetailTbl)("ilockboxModel.FK_DetailTbl_Batchtbl1", "DetailTbl")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DetailTbl)("ilockboxModel.FK_DetailTbl_Batchtbl1", "DetailTbl", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ilockboxModel", Name:="BatchValue")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class BatchValue 
    Inherits EntityObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new BatchValue object.
    ''' </summary>
    ''' <param name="workSource">Initial value of the WorkSource property.</param>
    ''' <param name="subSet">Initial value of the SubSet property.</param>
    ''' <param name="batchMode">Initial value of the BatchMode property.</param>
    ''' <param name="selectedBatchValue">Initial value of the SelectedBatchValue property.</param>
    Public Shared Function CreateBatchValue(workSource As Global.System.String, subSet As Global.System.Int16, batchMode As Global.System.Int16, selectedBatchValue As Global.System.Int16) As BatchValue
        Dim batchValue as BatchValue = New BatchValue
        batchValue.WorkSource = workSource
            
        batchValue.SubSet = subSet
            
        batchValue.BatchMode = batchMode
            
        batchValue.SelectedBatchValue = selectedBatchValue
            
        Return batchValue
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property WorkSource() As Global.System.String
        Get
            Return _WorkSource
        End Get
        Set
            If (WorkSource <> value) Then
                OnWorkSourceChanging(value)
                ReportPropertyChanging("WorkSource")
                _WorkSource = StructuralObject.SetValidValue(value, False)
                ReportPropertyChanged("WorkSource")
                OnWorkSourceChanged()
            End If
        End Set
    End Property
    
    Private _WorkSource as Global.System.String
    Private Partial Sub OnWorkSourceChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnWorkSourceChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SubSet() As Global.System.Int16
        Get
            Return _SubSet
        End Get
        Set
            If (SubSet <> value) Then
                OnSubSetChanging(value)
                ReportPropertyChanging("SubSet")
                _SubSet = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SubSet")
                OnSubSetChanged()
            End If
        End Set
    End Property
    
    Private _SubSet as Global.System.Int16
    Private Partial Sub OnSubSetChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnSubSetChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BatchMode() As Global.System.Int16
        Get
            Return _BatchMode
        End Get
        Set
            If (BatchMode <> value) Then
                OnBatchModeChanging(value)
                ReportPropertyChanging("BatchMode")
                _BatchMode = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("BatchMode")
                OnBatchModeChanged()
            End If
        End Set
    End Property
    
    Private _BatchMode as Global.System.Int16
    Private Partial Sub OnBatchModeChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnBatchModeChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SelectedBatchValue() As Global.System.Int16
        Get
            Return _SelectedBatchValue
        End Get
        Set
            OnSelectedBatchValueChanging(value)
            ReportPropertyChanging("SelectedBatchValue")
            _SelectedBatchValue = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SelectedBatchValue")
            OnSelectedBatchValueChanged()
        End Set
    End Property
    
    Private _SelectedBatchValue as Global.System.Int16
    Private Partial Sub OnSelectedBatchValueChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnSelectedBatchValueChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NextBatchValue() As Nullable(Of Global.System.Int16)
        Get
            Return _NextBatchValue
        End Get
        Set
            OnNextBatchValueChanging(value)
            ReportPropertyChanging("NextBatchValue")
            _NextBatchValue = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("NextBatchValue")
            OnNextBatchValueChanged()
        End Set
    End Property
    
    Private _NextBatchValue as Nullable(Of Global.System.Int16)
    Private Partial Sub OnNextBatchValueChanging(value As Nullable(Of Global.System.Int16))
    End Sub
    
    Private Partial Sub OnNextBatchValueChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property WaitToUpdate() As Global.System.String
        Get
            Return _WaitToUpdate
        End Get
        Set
            OnWaitToUpdateChanging(value)
            ReportPropertyChanging("WaitToUpdate")
            _WaitToUpdate = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("WaitToUpdate")
            OnWaitToUpdateChanged()
        End Set
    End Property
    
    Private _WaitToUpdate as Global.System.String
    Private Partial Sub OnWaitToUpdateChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnWaitToUpdateChanged()
    End Sub
    
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_BatchValue_Wrksrctbl", "Wrksrctbl")>
    Public Property Wrksrctbl() As Wrksrctbl
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_BatchValue_Wrksrctbl", "Wrksrctbl").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_BatchValue_Wrksrctbl", "Wrksrctbl").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property WrksrctblReference() As EntityReference(Of Wrksrctbl)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_BatchValue_Wrksrctbl", "Wrksrctbl")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_BatchValue_Wrksrctbl", "Wrksrctbl", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ilockboxModel", Name:="DetailTbl")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DetailTbl 
    Inherits EntityObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new DetailTbl object.
    ''' </summary>
    ''' <param name="siteId">Initial value of the SiteId property.</param>
    ''' <param name="processDt">Initial value of the ProcessDt property.</param>
    ''' <param name="workSource">Initial value of the WorkSource property.</param>
    ''' <param name="subSet">Initial value of the SubSet property.</param>
    ''' <param name="batchNumber">Initial value of the BatchNumber property.</param>
    ''' <param name="tranNo">Initial value of the TranNo property.</param>
    ''' <param name="seqNo">Initial value of the SeqNo property.</param>
    ''' <param name="subSeqNo">Initial value of the SubSeqNo property.</param>
    ''' <param name="itemType">Initial value of the ItemType property.</param>
    ''' <param name="batchType">Initial value of the BatchType property.</param>
    Public Shared Function CreateDetailTbl(siteId As Global.System.Int16, processDt As Global.System.DateTime, workSource As Global.System.String, subSet As Global.System.Int16, batchNumber As Global.System.String, tranNo As Global.System.Int32, seqNo As Global.System.Int32, subSeqNo As Global.System.Int32, itemType As Global.System.String, batchType As Global.System.Int16) As DetailTbl
        Dim detailTbl as DetailTbl = New DetailTbl
        detailTbl.SiteId = siteId
            
        detailTbl.ProcessDt = processDt
            
        detailTbl.WorkSource = workSource
            
        detailTbl.SubSet = subSet
            
        detailTbl.BatchNumber = batchNumber
            
        detailTbl.TranNo = tranNo
            
        detailTbl.SeqNo = seqNo
            
        detailTbl.SubSeqNo = subSeqNo
            
        detailTbl.ItemType = itemType
            
        detailTbl.BatchType = batchType
            
        Return detailTbl
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SiteId() As Global.System.Int16
        Get
            Return _SiteId
        End Get
        Set
            If (SiteId <> value) Then
                OnSiteIdChanging(value)
                ReportPropertyChanging("SiteId")
                _SiteId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SiteId")
                OnSiteIdChanged()
            End If
        End Set
    End Property
    
    Private _SiteId as Global.System.Int16
    Private Partial Sub OnSiteIdChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnSiteIdChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProcessDt() As Global.System.DateTime
        Get
            Return _ProcessDt
        End Get
        Set
            If (ProcessDt <> value) Then
                OnProcessDtChanging(value)
                ReportPropertyChanging("ProcessDt")
                _ProcessDt = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ProcessDt")
                OnProcessDtChanged()
            End If
        End Set
    End Property
    
    Private _ProcessDt as Global.System.DateTime
    Private Partial Sub OnProcessDtChanging(value As Global.System.DateTime)
    End Sub
    
    Private Partial Sub OnProcessDtChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property WorkSource() As Global.System.String
        Get
            Return _WorkSource
        End Get
        Set
            If (WorkSource <> value) Then
                OnWorkSourceChanging(value)
                ReportPropertyChanging("WorkSource")
                _WorkSource = StructuralObject.SetValidValue(value, False)
                ReportPropertyChanged("WorkSource")
                OnWorkSourceChanged()
            End If
        End Set
    End Property
    
    Private _WorkSource as Global.System.String
    Private Partial Sub OnWorkSourceChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnWorkSourceChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SubSet() As Global.System.Int16
        Get
            Return _SubSet
        End Get
        Set
            If (SubSet <> value) Then
                OnSubSetChanging(value)
                ReportPropertyChanging("SubSet")
                _SubSet = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SubSet")
                OnSubSetChanged()
            End If
        End Set
    End Property
    
    Private _SubSet as Global.System.Int16
    Private Partial Sub OnSubSetChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnSubSetChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BatchNumber() As Global.System.String
        Get
            Return _BatchNumber
        End Get
        Set
            If (BatchNumber <> value) Then
                OnBatchNumberChanging(value)
                ReportPropertyChanging("BatchNumber")
                _BatchNumber = StructuralObject.SetValidValue(value, False)
                ReportPropertyChanged("BatchNumber")
                OnBatchNumberChanged()
            End If
        End Set
    End Property
    
    Private _BatchNumber as Global.System.String
    Private Partial Sub OnBatchNumberChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnBatchNumberChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TranNo() As Global.System.Int32
        Get
            Return _TranNo
        End Get
        Set
            If (TranNo <> value) Then
                OnTranNoChanging(value)
                ReportPropertyChanging("TranNo")
                _TranNo = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("TranNo")
                OnTranNoChanged()
            End If
        End Set
    End Property
    
    Private _TranNo as Global.System.Int32
    Private Partial Sub OnTranNoChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnTranNoChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SeqNo() As Global.System.Int32
        Get
            Return _SeqNo
        End Get
        Set
            If (SeqNo <> value) Then
                OnSeqNoChanging(value)
                ReportPropertyChanging("SeqNo")
                _SeqNo = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SeqNo")
                OnSeqNoChanged()
            End If
        End Set
    End Property
    
    Private _SeqNo as Global.System.Int32
    Private Partial Sub OnSeqNoChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnSeqNoChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SubSeqNo() As Global.System.Int32
        Get
            Return _SubSeqNo
        End Get
        Set
            If (SubSeqNo <> value) Then
                OnSubSeqNoChanging(value)
                ReportPropertyChanging("SubSeqNo")
                _SubSeqNo = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SubSeqNo")
                OnSubSeqNoChanged()
            End If
        End Set
    End Property
    
    Private _SubSeqNo as Global.System.Int32
    Private Partial Sub OnSubSeqNoChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnSubSeqNoChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property P1ImgSeqNo() As Nullable(Of Global.System.Int32)
        Get
            Return _P1ImgSeqNo
        End Get
        Set
            OnP1ImgSeqNoChanging(value)
            ReportPropertyChanging("P1ImgSeqNo")
            _P1ImgSeqNo = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("P1ImgSeqNo")
            OnP1ImgSeqNoChanged()
        End Set
    End Property
    
    Private _P1ImgSeqNo as Nullable(Of Global.System.Int32)
    Private Partial Sub OnP1ImgSeqNoChanging(value As Nullable(Of Global.System.Int32))
    End Sub
    
    Private Partial Sub OnP1ImgSeqNoChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property P2ImgSeqNo() As Nullable(Of Global.System.Int32)
        Get
            Return _P2ImgSeqNo
        End Get
        Set
            OnP2ImgSeqNoChanging(value)
            ReportPropertyChanging("P2ImgSeqNo")
            _P2ImgSeqNo = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("P2ImgSeqNo")
            OnP2ImgSeqNoChanged()
        End Set
    End Property
    
    Private _P2ImgSeqNo as Nullable(Of Global.System.Int32)
    Private Partial Sub OnP2ImgSeqNoChanging(value As Nullable(Of Global.System.Int32))
    End Sub
    
    Private Partial Sub OnP2ImgSeqNoChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ItemType() As Global.System.String
        Get
            Return _ItemType
        End Get
        Set
            OnItemTypeChanging(value)
            ReportPropertyChanging("ItemType")
            _ItemType = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("ItemType")
            OnItemTypeChanged()
        End Set
    End Property
    
    Private _ItemType as Global.System.String
    Private Partial Sub OnItemTypeChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnItemTypeChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BatchType() As Global.System.Int16
        Get
            Return _BatchType
        End Get
        Set
            OnBatchTypeChanging(value)
            ReportPropertyChanging("BatchType")
            _BatchType = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("BatchType")
            OnBatchTypeChanged()
        End Set
    End Property
    
    Private _BatchType as Global.System.Int16
    Private Partial Sub OnBatchTypeChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnBatchTypeChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserFlag1() As Global.System.String
        Get
            Return _UserFlag1
        End Get
        Set
            OnUserFlag1Changing(value)
            ReportPropertyChanging("UserFlag1")
            _UserFlag1 = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("UserFlag1")
            OnUserFlag1Changed()
        End Set
    End Property
    
    Private _UserFlag1 as Global.System.String
    Private Partial Sub OnUserFlag1Changing(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnUserFlag1Changed()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserFlag2() As Global.System.String
        Get
            Return _UserFlag2
        End Get
        Set
            OnUserFlag2Changing(value)
            ReportPropertyChanging("UserFlag2")
            _UserFlag2 = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("UserFlag2")
            OnUserFlag2Changed()
        End Set
    End Property
    
    Private _UserFlag2 as Global.System.String
    Private Partial Sub OnUserFlag2Changing(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnUserFlag2Changed()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserFlag3() As Global.System.String
        Get
            Return _UserFlag3
        End Get
        Set
            OnUserFlag3Changing(value)
            ReportPropertyChanging("UserFlag3")
            _UserFlag3 = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("UserFlag3")
            OnUserFlag3Changed()
        End Set
    End Property
    
    Private _UserFlag3 as Global.System.String
    Private Partial Sub OnUserFlag3Changing(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnUserFlag3Changed()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserFlag4() As Global.System.String
        Get
            Return _UserFlag4
        End Get
        Set
            OnUserFlag4Changing(value)
            ReportPropertyChanging("UserFlag4")
            _UserFlag4 = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("UserFlag4")
            OnUserFlag4Changed()
        End Set
    End Property
    
    Private _UserFlag4 as Global.System.String
    Private Partial Sub OnUserFlag4Changing(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnUserFlag4Changed()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserInt1() As Nullable(Of Global.System.Int32)
        Get
            Return _UserInt1
        End Get
        Set
            OnUserInt1Changing(value)
            ReportPropertyChanging("UserInt1")
            _UserInt1 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UserInt1")
            OnUserInt1Changed()
        End Set
    End Property
    
    Private _UserInt1 as Nullable(Of Global.System.Int32)
    Private Partial Sub OnUserInt1Changing(value As Nullable(Of Global.System.Int32))
    End Sub
    
    Private Partial Sub OnUserInt1Changed()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserInt2() As Nullable(Of Global.System.Int32)
        Get
            Return _UserInt2
        End Get
        Set
            OnUserInt2Changing(value)
            ReportPropertyChanging("UserInt2")
            _UserInt2 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UserInt2")
            OnUserInt2Changed()
        End Set
    End Property
    
    Private _UserInt2 as Nullable(Of Global.System.Int32)
    Private Partial Sub OnUserInt2Changing(value As Nullable(Of Global.System.Int32))
    End Sub
    
    Private Partial Sub OnUserInt2Changed()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserInt3() As Nullable(Of Global.System.Int32)
        Get
            Return _UserInt3
        End Get
        Set
            OnUserInt3Changing(value)
            ReportPropertyChanging("UserInt3")
            _UserInt3 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UserInt3")
            OnUserInt3Changed()
        End Set
    End Property
    
    Private _UserInt3 as Nullable(Of Global.System.Int32)
    Private Partial Sub OnUserInt3Changing(value As Nullable(Of Global.System.Int32))
    End Sub
    
    Private Partial Sub OnUserInt3Changed()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserString1() As Global.System.String
        Get
            Return _UserString1
        End Get
        Set
            OnUserString1Changing(value)
            ReportPropertyChanging("UserString1")
            _UserString1 = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("UserString1")
            OnUserString1Changed()
        End Set
    End Property
    
    Private _UserString1 as Global.System.String
    Private Partial Sub OnUserString1Changing(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnUserString1Changed()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserString2() As Global.System.String
        Get
            Return _UserString2
        End Get
        Set
            OnUserString2Changing(value)
            ReportPropertyChanging("UserString2")
            _UserString2 = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("UserString2")
            OnUserString2Changed()
        End Set
    End Property
    
    Private _UserString2 as Global.System.String
    Private Partial Sub OnUserString2Changing(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnUserString2Changed()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserString3() As Global.System.String
        Get
            Return _UserString3
        End Get
        Set
            OnUserString3Changing(value)
            ReportPropertyChanging("UserString3")
            _UserString3 = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("UserString3")
            OnUserString3Changed()
        End Set
    End Property
    
    Private _UserString3 as Global.System.String
    Private Partial Sub OnUserString3Changing(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnUserString3Changed()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SubType() As Global.System.String
        Get
            Return _SubType
        End Get
        Set
            OnSubTypeChanging(value)
            ReportPropertyChanging("SubType")
            _SubType = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("SubType")
            OnSubTypeChanged()
        End Set
    End Property
    
    Private _SubType as Global.System.String
    Private Partial Sub OnSubTypeChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnSubTypeChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserFlag5() As Global.System.String
        Get
            Return _UserFlag5
        End Get
        Set
            OnUserFlag5Changing(value)
            ReportPropertyChanging("UserFlag5")
            _UserFlag5 = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("UserFlag5")
            OnUserFlag5Changed()
        End Set
    End Property
    
    Private _UserFlag5 as Global.System.String
    Private Partial Sub OnUserFlag5Changing(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnUserFlag5Changed()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserFlag6() As Global.System.String
        Get
            Return _UserFlag6
        End Get
        Set
            OnUserFlag6Changing(value)
            ReportPropertyChanging("UserFlag6")
            _UserFlag6 = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("UserFlag6")
            OnUserFlag6Changed()
        End Set
    End Property
    
    Private _UserFlag6 as Global.System.String
    Private Partial Sub OnUserFlag6Changing(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnUserFlag6Changed()
    End Sub
    
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_DetailTbl_Batchtbl1", "Batchtbl")>
    Public Property Batchtbl() As Batchtbl
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Batchtbl)("ilockboxModel.FK_DetailTbl_Batchtbl1", "Batchtbl").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Batchtbl)("ilockboxModel.FK_DetailTbl_Batchtbl1", "Batchtbl").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property BatchtblReference() As EntityReference(Of Batchtbl)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Batchtbl)("ilockboxModel.FK_DetailTbl_Batchtbl1", "Batchtbl")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Batchtbl)("ilockboxModel.FK_DetailTbl_Batchtbl1", "Batchtbl", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ilockboxModel", Name:="ImgTbl")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ImgTbl 
    Inherits EntityObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new ImgTbl object.
    ''' </summary>
    ''' <param name="workSource">Initial value of the WorkSource property.</param>
    ''' <param name="subSet">Initial value of the SubSet property.</param>
    ''' <param name="batchMode">Initial value of the BatchMode property.</param>
    ''' <param name="imageDisp">Initial value of the ImageDisp property.</param>
    ''' <param name="imagePost">Initial value of the ImagePost property.</param>
    Public Shared Function CreateImgTbl(workSource As Global.System.String, subSet As Global.System.Int16, batchMode As Global.System.Int16, imageDisp As Global.System.String, imagePost As Global.System.String) As ImgTbl
        Dim imgTbl as ImgTbl = New ImgTbl
        imgTbl.WorkSource = workSource
            
        imgTbl.SubSet = subSet
            
        imgTbl.BatchMode = batchMode
            
        imgTbl.ImageDisp = imageDisp
            
        imgTbl.ImagePost = imagePost
            
        Return imgTbl
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property WorkSource() As Global.System.String
        Get
            Return _WorkSource
        End Get
        Set
            If (WorkSource <> value) Then
                OnWorkSourceChanging(value)
                ReportPropertyChanging("WorkSource")
                _WorkSource = StructuralObject.SetValidValue(value, False)
                ReportPropertyChanged("WorkSource")
                OnWorkSourceChanged()
            End If
        End Set
    End Property
    
    Private _WorkSource as Global.System.String
    Private Partial Sub OnWorkSourceChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnWorkSourceChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SubSet() As Global.System.Int16
        Get
            Return _SubSet
        End Get
        Set
            If (SubSet <> value) Then
                OnSubSetChanging(value)
                ReportPropertyChanging("SubSet")
                _SubSet = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SubSet")
                OnSubSetChanged()
            End If
        End Set
    End Property
    
    Private _SubSet as Global.System.Int16
    Private Partial Sub OnSubSetChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnSubSetChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BatchMode() As Global.System.Int16
        Get
            Return _BatchMode
        End Get
        Set
            If (BatchMode <> value) Then
                OnBatchModeChanging(value)
                ReportPropertyChanging("BatchMode")
                _BatchMode = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("BatchMode")
                OnBatchModeChanged()
            End If
        End Set
    End Property
    
    Private _BatchMode as Global.System.Int16
    Private Partial Sub OnBatchModeChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnBatchModeChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ImageDisp() As Global.System.String
        Get
            Return _ImageDisp
        End Get
        Set
            OnImageDispChanging(value)
            ReportPropertyChanging("ImageDisp")
            _ImageDisp = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("ImageDisp")
            OnImageDispChanged()
        End Set
    End Property
    
    Private _ImageDisp as Global.System.String
    Private Partial Sub OnImageDispChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnImageDispChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ImagePost() As Global.System.String
        Get
            Return _ImagePost
        End Get
        Set
            OnImagePostChanging(value)
            ReportPropertyChanging("ImagePost")
            _ImagePost = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("ImagePost")
            OnImagePostChanged()
        End Set
    End Property
    
    Private _ImagePost as Global.System.String
    Private Partial Sub OnImagePostChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnImagePostChanged()
    End Sub
    
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_ImgTbl_Wrksrctbl", "Wrksrctbl")>
    Public Property Wrksrctbl() As Wrksrctbl
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_ImgTbl_Wrksrctbl", "Wrksrctbl").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_ImgTbl_Wrksrctbl", "Wrksrctbl").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property WrksrctblReference() As EntityReference(Of Wrksrctbl)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_ImgTbl_Wrksrctbl", "Wrksrctbl")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_ImgTbl_Wrksrctbl", "Wrksrctbl", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ilockboxModel", Name:="ItemSelectTbl")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ItemSelectTbl 
    Inherits EntityObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new ItemSelectTbl object.
    ''' </summary>
    ''' <param name="workSource">Initial value of the WorkSource property.</param>
    ''' <param name="subSet">Initial value of the SubSet property.</param>
    ''' <param name="batchMode">Initial value of the BatchMode property.</param>
    ''' <param name="itemDisp">Initial value of the ItemDisp property.</param>
    ''' <param name="itemPost">Initial value of the ItemPost property.</param>
    Public Shared Function CreateItemSelectTbl(workSource As Global.System.String, subSet As Global.System.Int16, batchMode As Global.System.Int16, itemDisp As Global.System.String, itemPost As Global.System.String) As ItemSelectTbl
        Dim itemSelectTbl as ItemSelectTbl = New ItemSelectTbl
        itemSelectTbl.WorkSource = workSource
            
        itemSelectTbl.SubSet = subSet
            
        itemSelectTbl.BatchMode = batchMode
            
        itemSelectTbl.ItemDisp = itemDisp
            
        itemSelectTbl.ItemPost = itemPost
            
        Return itemSelectTbl
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property WorkSource() As Global.System.String
        Get
            Return _WorkSource
        End Get
        Set
            If (WorkSource <> value) Then
                OnWorkSourceChanging(value)
                ReportPropertyChanging("WorkSource")
                _WorkSource = StructuralObject.SetValidValue(value, False)
                ReportPropertyChanged("WorkSource")
                OnWorkSourceChanged()
            End If
        End Set
    End Property
    
    Private _WorkSource as Global.System.String
    Private Partial Sub OnWorkSourceChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnWorkSourceChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SubSet() As Global.System.Int16
        Get
            Return _SubSet
        End Get
        Set
            If (SubSet <> value) Then
                OnSubSetChanging(value)
                ReportPropertyChanging("SubSet")
                _SubSet = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SubSet")
                OnSubSetChanged()
            End If
        End Set
    End Property
    
    Private _SubSet as Global.System.Int16
    Private Partial Sub OnSubSetChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnSubSetChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BatchMode() As Global.System.Int16
        Get
            Return _BatchMode
        End Get
        Set
            If (BatchMode <> value) Then
                OnBatchModeChanging(value)
                ReportPropertyChanging("BatchMode")
                _BatchMode = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("BatchMode")
                OnBatchModeChanged()
            End If
        End Set
    End Property
    
    Private _BatchMode as Global.System.Int16
    Private Partial Sub OnBatchModeChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnBatchModeChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ItemDisp() As Global.System.String
        Get
            Return _ItemDisp
        End Get
        Set
            OnItemDispChanging(value)
            ReportPropertyChanging("ItemDisp")
            _ItemDisp = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("ItemDisp")
            OnItemDispChanged()
        End Set
    End Property
    
    Private _ItemDisp as Global.System.String
    Private Partial Sub OnItemDispChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnItemDispChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ItemPost() As Global.System.String
        Get
            Return _ItemPost
        End Get
        Set
            OnItemPostChanging(value)
            ReportPropertyChanging("ItemPost")
            _ItemPost = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("ItemPost")
            OnItemPostChanged()
        End Set
    End Property
    
    Private _ItemPost as Global.System.String
    Private Partial Sub OnItemPostChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnItemPostChanged()
    End Sub
    
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_ItemSelectTbl_Wrksrctbl", "Wrksrctbl")>
    Public Property Wrksrctbl() As Wrksrctbl
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_ItemSelectTbl_Wrksrctbl", "Wrksrctbl").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_ItemSelectTbl_Wrksrctbl", "Wrksrctbl").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property WrksrctblReference() As EntityReference(Of Wrksrctbl)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_ItemSelectTbl_Wrksrctbl", "Wrksrctbl")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Wrksrctbl)("ilockboxModel.FK_ItemSelectTbl_Wrksrctbl", "Wrksrctbl", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ilockboxModel", Name:="Wrksrctbl")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Wrksrctbl 
    Inherits EntityObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new Wrksrctbl object.
    ''' </summary>
    ''' <param name="workSource">Initial value of the WorkSource property.</param>
    ''' <param name="subSet">Initial value of the SubSet property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="imagePath">Initial value of the ImagePath property.</param>
    ''' <param name="xmlPath">Initial value of the XmlPath property.</param>
    ''' <param name="autoTrans">Initial value of the AutoTrans property.</param>
    ''' <param name="belongsToGroup">Initial value of the BelongsToGroup property.</param>
    ''' <param name="siteID">Initial value of the SiteID property.</param>
    ''' <param name="isItActive">Initial value of the IsItActive property.</param>
    Public Shared Function CreateWrksrctbl(workSource As Global.System.String, subSet As Global.System.Int16, name As Global.System.String, imagePath As Global.System.String, xmlPath As Global.System.String, autoTrans As Global.System.String, belongsToGroup As Global.System.String, siteID As Global.System.Int16, isItActive As Global.System.String) As Wrksrctbl
        Dim wrksrctbl as Wrksrctbl = New Wrksrctbl
        wrksrctbl.WorkSource = workSource
            
        wrksrctbl.SubSet = subSet
            
        wrksrctbl.Name = name
            
        wrksrctbl.ImagePath = imagePath
            
        wrksrctbl.XmlPath = xmlPath
            
        wrksrctbl.AutoTrans = autoTrans
            
        wrksrctbl.BelongsToGroup = belongsToGroup
            
        wrksrctbl.SiteID = siteID
            
        wrksrctbl.IsItActive = isItActive
            
        Return wrksrctbl
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property WorkSource() As Global.System.String
        Get
            Return _WorkSource
        End Get
        Set
            If (WorkSource <> value) Then
                OnWorkSourceChanging(value)
                ReportPropertyChanging("WorkSource")
                _WorkSource = StructuralObject.SetValidValue(value, False)
                ReportPropertyChanged("WorkSource")
                OnWorkSourceChanged()
            End If
        End Set
    End Property
    
    Private _WorkSource as Global.System.String
    Private Partial Sub OnWorkSourceChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnWorkSourceChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SubSet() As Global.System.Int16
        Get
            Return _SubSet
        End Get
        Set
            If (SubSet <> value) Then
                OnSubSetChanging(value)
                ReportPropertyChanging("SubSet")
                _SubSet = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SubSet")
                OnSubSetChanged()
            End If
        End Set
    End Property
    
    Private _SubSet as Global.System.Int16
    Private Partial Sub OnSubSetChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnSubSetChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property
    
    Private _Name as Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnNameChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ImagePath() As Global.System.String
        Get
            Return _ImagePath
        End Get
        Set
            OnImagePathChanging(value)
            ReportPropertyChanging("ImagePath")
            _ImagePath = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("ImagePath")
            OnImagePathChanged()
        End Set
    End Property
    
    Private _ImagePath as Global.System.String
    Private Partial Sub OnImagePathChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnImagePathChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property XmlPath() As Global.System.String
        Get
            Return _XmlPath
        End Get
        Set
            OnXmlPathChanging(value)
            ReportPropertyChanging("XmlPath")
            _XmlPath = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("XmlPath")
            OnXmlPathChanged()
        End Set
    End Property
    
    Private _XmlPath as Global.System.String
    Private Partial Sub OnXmlPathChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnXmlPathChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AutoTrans() As Global.System.String
        Get
            Return _AutoTrans
        End Get
        Set
            OnAutoTransChanging(value)
            ReportPropertyChanging("AutoTrans")
            _AutoTrans = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("AutoTrans")
            OnAutoTransChanged()
        End Set
    End Property
    
    Private _AutoTrans as Global.System.String
    Private Partial Sub OnAutoTransChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnAutoTransChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BelongsToGroup() As Global.System.String
        Get
            Return _BelongsToGroup
        End Get
        Set
            OnBelongsToGroupChanging(value)
            ReportPropertyChanging("BelongsToGroup")
            _BelongsToGroup = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("BelongsToGroup")
            OnBelongsToGroupChanged()
        End Set
    End Property
    
    Private _BelongsToGroup as Global.System.String
    Private Partial Sub OnBelongsToGroupChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnBelongsToGroupChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property XmlImagePath() As Global.System.String
        Get
            Return _XmlImagePath
        End Get
        Set
            OnXmlImagePathChanging(value)
            ReportPropertyChanging("XmlImagePath")
            _XmlImagePath = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("XmlImagePath")
            OnXmlImagePathChanged()
        End Set
    End Property
    
    Private _XmlImagePath as Global.System.String
    Private Partial Sub OnXmlImagePathChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnXmlImagePathChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SiteID() As Global.System.Int16
        Get
            Return _SiteID
        End Get
        Set
            OnSiteIDChanging(value)
            ReportPropertyChanging("SiteID")
            _SiteID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SiteID")
            OnSiteIDChanged()
        End Set
    End Property
    
    Private _SiteID as Global.System.Int16
    Private Partial Sub OnSiteIDChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnSiteIDChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ItemFilter() As Global.System.String
        Get
            Return _ItemFilter
        End Get
        Set
            OnItemFilterChanging(value)
            ReportPropertyChanging("ItemFilter")
            _ItemFilter = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("ItemFilter")
            OnItemFilterChanged()
        End Set
    End Property
    
    Private _ItemFilter as Global.System.String
    Private Partial Sub OnItemFilterChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnItemFilterChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IsItActive() As Global.System.String
        Get
            Return _IsItActive
        End Get
        Set
            OnIsItActiveChanging(value)
            ReportPropertyChanging("IsItActive")
            _IsItActive = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("IsItActive")
            OnIsItActiveChanged()
        End Set
    End Property
    
    Private _IsItActive as Global.System.String
    Private Partial Sub OnIsItActiveChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnIsItActiveChanged()
    End Sub
    
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_Batchmodetbl_Wrksrctbl1", "Batchmodetbl")>
     Public Property Batchmodetbl() As EntityCollection(Of Batchmodetbl)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Batchmodetbl)("ilockboxModel.FK_Batchmodetbl_Wrksrctbl1", "Batchmodetbl")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Batchmodetbl)("ilockboxModel.FK_Batchmodetbl_Wrksrctbl1", "Batchmodetbl", value)
            End If
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_Batchtbl_Wrksrctbl", "Batchtbl")>
     Public Property Batchtbl() As EntityCollection(Of Batchtbl)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Batchtbl)("ilockboxModel.FK_Batchtbl_Wrksrctbl", "Batchtbl")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Batchtbl)("ilockboxModel.FK_Batchtbl_Wrksrctbl", "Batchtbl", value)
            End If
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_BatchValue_Wrksrctbl", "BatchValue")>
     Public Property BatchValue() As EntityCollection(Of BatchValue)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of BatchValue)("ilockboxModel.FK_BatchValue_Wrksrctbl", "BatchValue")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of BatchValue)("ilockboxModel.FK_BatchValue_Wrksrctbl", "BatchValue", value)
            End If
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_ImgTbl_Wrksrctbl", "ImgTbl")>
     Public Property ImgTbl() As EntityCollection(Of ImgTbl)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ImgTbl)("ilockboxModel.FK_ImgTbl_Wrksrctbl", "ImgTbl")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ImgTbl)("ilockboxModel.FK_ImgTbl_Wrksrctbl", "ImgTbl", value)
            End If
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ilockboxModel", "FK_ItemSelectTbl_Wrksrctbl", "ItemSelectTbl")>
     Public Property ItemSelectTbl() As EntityCollection(Of ItemSelectTbl)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ItemSelectTbl)("ilockboxModel.FK_ItemSelectTbl_Wrksrctbl", "ItemSelectTbl")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ItemSelectTbl)("ilockboxModel.FK_ItemSelectTbl_Wrksrctbl", "ItemSelectTbl", value)
            End If
        End Set
    End Property
    #End Region
End Class

#End Region

