'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.20506.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Original file name:
'Generation date: 5/25/2009 10:28:19 PM
Namespace ServiceReference1
    '''<summary>
    '''There are no comments for ilockboxEntities in the schema.
    '''</summary>
    Partial Public Class ilockboxEntities
        Inherits Global.System.Data.Services.Client.DataServiceContext
        '''<summary>
        '''Initialize a new ilockboxEntities object.
        '''</summary>
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot)
            Me.ResolveName = AddressOf Me.ResolveNameFromType
            Me.ResolveType = AddressOf Me.ResolveTypeFromName
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        Private Shared ROOTNAMESPACE As String = GetType(ServiceReference1.ilockboxEntities).Namespace.Remove(GetType(ServiceReference1.ilockboxEntities).Namespace.LastIndexOf("ServiceReference1"))
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
            If typeName.StartsWith("ilockboxModel", Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return Me.GetType.Assembly.GetType(String.Concat(String.Concat(ROOTNAMESPACE, "ServiceReference1"), typeName.Substring(13)), true)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
            If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "ServiceReference1"), Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return String.Concat("ilockboxModel.", clientType.Name)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''There are no comments for Batchmodetbl in the schema.
        '''</summary>
        Public ReadOnly Property Batchmodetbl() As Global.System.Data.Services.Client.DataServiceQuery(Of Batchmodetbl)
            Get
                If (Me._Batchmodetbl Is Nothing) Then
                    Me._Batchmodetbl = MyBase.CreateQuery(Of Batchmodetbl)("Batchmodetbl")
                End If
                Return Me._Batchmodetbl
            End Get
        End Property
        Private _Batchmodetbl As Global.System.Data.Services.Client.DataServiceQuery(Of Batchmodetbl)
        '''<summary>
        '''There are no comments for Batchtbl in the schema.
        '''</summary>
        Public ReadOnly Property Batchtbl() As Global.System.Data.Services.Client.DataServiceQuery(Of Batchtbl)
            Get
                If (Me._Batchtbl Is Nothing) Then
                    Me._Batchtbl = MyBase.CreateQuery(Of Batchtbl)("Batchtbl")
                End If
                Return Me._Batchtbl
            End Get
        End Property
        Private _Batchtbl As Global.System.Data.Services.Client.DataServiceQuery(Of Batchtbl)
        '''<summary>
        '''There are no comments for BatchValue in the schema.
        '''</summary>
        Public ReadOnly Property BatchValue() As Global.System.Data.Services.Client.DataServiceQuery(Of BatchValue)
            Get
                If (Me._BatchValue Is Nothing) Then
                    Me._BatchValue = MyBase.CreateQuery(Of BatchValue)("BatchValue")
                End If
                Return Me._BatchValue
            End Get
        End Property
        Private _BatchValue As Global.System.Data.Services.Client.DataServiceQuery(Of BatchValue)
        '''<summary>
        '''There are no comments for DetailTbl in the schema.
        '''</summary>
        Public ReadOnly Property DetailTbl() As Global.System.Data.Services.Client.DataServiceQuery(Of DetailTbl)
            Get
                If (Me._DetailTbl Is Nothing) Then
                    Me._DetailTbl = MyBase.CreateQuery(Of DetailTbl)("DetailTbl")
                End If
                Return Me._DetailTbl
            End Get
        End Property
        Private _DetailTbl As Global.System.Data.Services.Client.DataServiceQuery(Of DetailTbl)
        '''<summary>
        '''There are no comments for ImgTbl in the schema.
        '''</summary>
        Public ReadOnly Property ImgTbl() As Global.System.Data.Services.Client.DataServiceQuery(Of ImgTbl)
            Get
                If (Me._ImgTbl Is Nothing) Then
                    Me._ImgTbl = MyBase.CreateQuery(Of ImgTbl)("ImgTbl")
                End If
                Return Me._ImgTbl
            End Get
        End Property
        Private _ImgTbl As Global.System.Data.Services.Client.DataServiceQuery(Of ImgTbl)
        '''<summary>
        '''There are no comments for ItemSelectTbl in the schema.
        '''</summary>
        Public ReadOnly Property ItemSelectTbl() As Global.System.Data.Services.Client.DataServiceQuery(Of ItemSelectTbl)
            Get
                If (Me._ItemSelectTbl Is Nothing) Then
                    Me._ItemSelectTbl = MyBase.CreateQuery(Of ItemSelectTbl)("ItemSelectTbl")
                End If
                Return Me._ItemSelectTbl
            End Get
        End Property
        Private _ItemSelectTbl As Global.System.Data.Services.Client.DataServiceQuery(Of ItemSelectTbl)
        '''<summary>
        '''There are no comments for RegionCodes in the schema.
        '''</summary>
        Public ReadOnly Property RegionCodes() As Global.System.Data.Services.Client.DataServiceQuery(Of RegionCodes)
            Get
                If (Me._RegionCodes Is Nothing) Then
                    Me._RegionCodes = MyBase.CreateQuery(Of RegionCodes)("RegionCodes")
                End If
                Return Me._RegionCodes
            End Get
        End Property
        Private _RegionCodes As Global.System.Data.Services.Client.DataServiceQuery(Of RegionCodes)
        '''<summary>
        '''There are no comments for Wrksrctbl in the schema.
        '''</summary>
        Public ReadOnly Property Wrksrctbl() As Global.System.Data.Services.Client.DataServiceQuery(Of Wrksrctbl)
            Get
                If (Me._Wrksrctbl Is Nothing) Then
                    Me._Wrksrctbl = MyBase.CreateQuery(Of Wrksrctbl)("Wrksrctbl")
                End If
                Return Me._Wrksrctbl
            End Get
        End Property
        Private _Wrksrctbl As Global.System.Data.Services.Client.DataServiceQuery(Of Wrksrctbl)
        '''<summary>
        '''There are no comments for Batchmodetbl in the schema.
        '''</summary>
        Public Sub AddToBatchmodetbl(ByVal batchmodetbl As Batchmodetbl)
            MyBase.AddObject("Batchmodetbl", batchmodetbl)
        End Sub
        '''<summary>
        '''There are no comments for Batchtbl in the schema.
        '''</summary>
        Public Sub AddToBatchtbl(ByVal batchtbl As Batchtbl)
            MyBase.AddObject("Batchtbl", batchtbl)
        End Sub
        '''<summary>
        '''There are no comments for BatchValue in the schema.
        '''</summary>
        Public Sub AddToBatchValue(ByVal batchValue As BatchValue)
            MyBase.AddObject("BatchValue", batchValue)
        End Sub
        '''<summary>
        '''There are no comments for DetailTbl in the schema.
        '''</summary>
        Public Sub AddToDetailTbl(ByVal detailTbl As DetailTbl)
            MyBase.AddObject("DetailTbl", detailTbl)
        End Sub
        '''<summary>
        '''There are no comments for ImgTbl in the schema.
        '''</summary>
        Public Sub AddToImgTbl(ByVal imgTbl As ImgTbl)
            MyBase.AddObject("ImgTbl", imgTbl)
        End Sub
        '''<summary>
        '''There are no comments for ItemSelectTbl in the schema.
        '''</summary>
        Public Sub AddToItemSelectTbl(ByVal itemSelectTbl As ItemSelectTbl)
            MyBase.AddObject("ItemSelectTbl", itemSelectTbl)
        End Sub
        '''<summary>
        '''There are no comments for RegionCodes in the schema.
        '''</summary>
        Public Sub AddToRegionCodes(ByVal regionCodes As RegionCodes)
            MyBase.AddObject("RegionCodes", regionCodes)
        End Sub
        '''<summary>
        '''There are no comments for Wrksrctbl in the schema.
        '''</summary>
        Public Sub AddToWrksrctbl(ByVal wrksrctbl As Wrksrctbl)
            MyBase.AddObject("Wrksrctbl", wrksrctbl)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for ilockboxModel.Batchmodetbl in the schema.
    '''</summary>
    '''<KeyProperties>
    '''WorkSource
    '''SubSet
    '''BatchMode
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("WorkSource", "SubSet", "BatchMode")>  _
    Partial Public Class Batchmodetbl
        '''<summary>
        '''Create a new Batchmodetbl object.
        '''</summary>
        '''<param name="workSource">Initial value of WorkSource.</param>
        '''<param name="subSet">Initial value of SubSet.</param>
        '''<param name="batchMode">Initial value of BatchMode.</param>
        Public Shared Function CreateBatchmodetbl(ByVal workSource As String, ByVal subSet As Short, ByVal batchMode As Short) As Batchmodetbl
            Dim batchmodetbl As Batchmodetbl = New Batchmodetbl()
            batchmodetbl.WorkSource = workSource
            batchmodetbl.SubSet = subSet
            batchmodetbl.BatchMode = batchMode
            Return batchmodetbl
        End Function
        '''<summary>
        '''There are no comments for Property WorkSource in the schema.
        '''</summary>
        Public Property WorkSource() As String
            Get
                Return Me._WorkSource
            End Get
            Set
                Me.OnWorkSourceChanging(value)
                Me._WorkSource = value
                Me.OnWorkSourceChanged
            End Set
        End Property
        Private _WorkSource As String
        Partial Private Sub OnWorkSourceChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnWorkSourceChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SubSet in the schema.
        '''</summary>
        Public Property SubSet() As Short
            Get
                Return Me._SubSet
            End Get
            Set
                Me.OnSubSetChanging(value)
                Me._SubSet = value
                Me.OnSubSetChanged
            End Set
        End Property
        Private _SubSet As Short
        Partial Private Sub OnSubSetChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnSubSetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BatchMode in the schema.
        '''</summary>
        Public Property BatchMode() As Short
            Get
                Return Me._BatchMode
            End Get
            Set
                Me.OnBatchModeChanging(value)
                Me._BatchMode = value
                Me.OnBatchModeChanged
            End Set
        End Property
        Private _BatchMode As Short
        Partial Private Sub OnBatchModeChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnBatchModeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
            End Set
        End Property
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Wrksrctbl in the schema.
        '''</summary>
        Public Property Wrksrctbl() As Wrksrctbl
            Get
                Return Me._Wrksrctbl
            End Get
            Set
                Me._Wrksrctbl = value
            End Set
        End Property
        Private _Wrksrctbl As Wrksrctbl
    End Class
    '''<summary>
    '''There are no comments for ilockboxModel.Batchtbl in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ProcessDt
    '''WorkSource
    '''SubSet
    '''BatchNumber
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("ProcessDt", "WorkSource", "SubSet", "BatchNumber")>  _
    Partial Public Class Batchtbl
        '''<summary>
        '''Create a new Batchtbl object.
        '''</summary>
        '''<param name="processDt">Initial value of ProcessDt.</param>
        '''<param name="workSource">Initial value of WorkSource.</param>
        '''<param name="subSet">Initial value of SubSet.</param>
        '''<param name="batchNumber">Initial value of BatchNumber.</param>
        Public Shared Function CreateBatchtbl(ByVal processDt As Date, ByVal workSource As String, ByVal subSet As Short, ByVal batchNumber As String) As Batchtbl
            Dim batchtbl As Batchtbl = New Batchtbl()
            batchtbl.ProcessDt = processDt
            batchtbl.WorkSource = workSource
            batchtbl.SubSet = subSet
            batchtbl.BatchNumber = batchNumber
            Return batchtbl
        End Function
        '''<summary>
        '''There are no comments for Property ProcessDt in the schema.
        '''</summary>
        Public Property ProcessDt() As Date
            Get
                Return Me._ProcessDt
            End Get
            Set
                Me.OnProcessDtChanging(value)
                Me._ProcessDt = value
                Me.OnProcessDtChanged
            End Set
        End Property
        Private _ProcessDt As Date
        Partial Private Sub OnProcessDtChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnProcessDtChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property WorkSource in the schema.
        '''</summary>
        Public Property WorkSource() As String
            Get
                Return Me._WorkSource
            End Get
            Set
                Me.OnWorkSourceChanging(value)
                Me._WorkSource = value
                Me.OnWorkSourceChanged
            End Set
        End Property
        Private _WorkSource As String
        Partial Private Sub OnWorkSourceChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnWorkSourceChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SubSet in the schema.
        '''</summary>
        Public Property SubSet() As Short
            Get
                Return Me._SubSet
            End Get
            Set
                Me.OnSubSetChanging(value)
                Me._SubSet = value
                Me.OnSubSetChanged
            End Set
        End Property
        Private _SubSet As Short
        Partial Private Sub OnSubSetChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnSubSetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BatchNumber in the schema.
        '''</summary>
        Public Property BatchNumber() As String
            Get
                Return Me._BatchNumber
            End Get
            Set
                Me.OnBatchNumberChanging(value)
                Me._BatchNumber = value
                Me.OnBatchNumberChanged
            End Set
        End Property
        Private _BatchNumber As String
        Partial Private Sub OnBatchNumberChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnBatchNumberChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Status in the schema.
        '''</summary>
        Public Property Status() As String
            Get
                Return Me._Status
            End Get
            Set
                Me.OnStatusChanging(value)
                Me._Status = value
                Me.OnStatusChanged
            End Set
        End Property
        Private _Status As String
        Partial Private Sub OnStatusChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnStatusChanged()
        End Sub
        '''<summary>
        '''There are no comments for Wrksrctbl in the schema.
        '''</summary>
        Public Property Wrksrctbl() As Wrksrctbl
            Get
                Return Me._Wrksrctbl
            End Get
            Set
                Me._Wrksrctbl = value
            End Set
        End Property
        Private _Wrksrctbl As Wrksrctbl
        '''<summary>
        '''There are no comments for DetailTbl in the schema.
        '''</summary>
        Public Property DetailTbl() As Global.System.Collections.ObjectModel.Collection(Of DetailTbl)
            Get
                Return Me._DetailTbl
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    Me._DetailTbl = value
                End If
            End Set
        End Property
        Private _DetailTbl As Global.System.Collections.ObjectModel.Collection(Of DetailTbl) = New Global.System.Collections.ObjectModel.Collection(Of DetailTbl)()
    End Class
    '''<summary>
    '''There are no comments for ilockboxModel.BatchValue in the schema.
    '''</summary>
    '''<KeyProperties>
    '''WorkSource
    '''SubSet
    '''BatchMode
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("WorkSource", "SubSet", "BatchMode")>  _
    Partial Public Class BatchValue
        '''<summary>
        '''Create a new BatchValue object.
        '''</summary>
        '''<param name="workSource">Initial value of WorkSource.</param>
        '''<param name="subSet">Initial value of SubSet.</param>
        '''<param name="batchMode">Initial value of BatchMode.</param>
        '''<param name="selectedBatchValue">Initial value of SelectedBatchValue.</param>
        Public Shared Function CreateBatchValue(ByVal workSource As String, ByVal subSet As Short, ByVal batchMode As Short, ByVal selectedBatchValue As Short) As BatchValue
            Dim batchValue As BatchValue = New BatchValue()
            batchValue.WorkSource = workSource
            batchValue.SubSet = subSet
            batchValue.BatchMode = batchMode
            batchValue.SelectedBatchValue = selectedBatchValue
            Return batchValue
        End Function
        '''<summary>
        '''There are no comments for Property WorkSource in the schema.
        '''</summary>
        Public Property WorkSource() As String
            Get
                Return Me._WorkSource
            End Get
            Set
                Me.OnWorkSourceChanging(value)
                Me._WorkSource = value
                Me.OnWorkSourceChanged
            End Set
        End Property
        Private _WorkSource As String
        Partial Private Sub OnWorkSourceChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnWorkSourceChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SubSet in the schema.
        '''</summary>
        Public Property SubSet() As Short
            Get
                Return Me._SubSet
            End Get
            Set
                Me.OnSubSetChanging(value)
                Me._SubSet = value
                Me.OnSubSetChanged
            End Set
        End Property
        Private _SubSet As Short
        Partial Private Sub OnSubSetChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnSubSetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BatchMode in the schema.
        '''</summary>
        Public Property BatchMode() As Short
            Get
                Return Me._BatchMode
            End Get
            Set
                Me.OnBatchModeChanging(value)
                Me._BatchMode = value
                Me.OnBatchModeChanged
            End Set
        End Property
        Private _BatchMode As Short
        Partial Private Sub OnBatchModeChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnBatchModeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SelectedBatchValue in the schema.
        '''</summary>
        Public Property SelectedBatchValue() As Short
            Get
                Return Me._SelectedBatchValue
            End Get
            Set
                Me.OnSelectedBatchValueChanging(value)
                Me._SelectedBatchValue = value
                Me.OnSelectedBatchValueChanged
            End Set
        End Property
        Private _SelectedBatchValue As Short
        Partial Private Sub OnSelectedBatchValueChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnSelectedBatchValueChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property NextBatchValue in the schema.
        '''</summary>
        Public Property NextBatchValue() As Global.System.Nullable(Of Short)
            Get
                Return Me._NextBatchValue
            End Get
            Set
                Me.OnNextBatchValueChanging(value)
                Me._NextBatchValue = value
                Me.OnNextBatchValueChanged
            End Set
        End Property
        Private _NextBatchValue As Global.System.Nullable(Of Short)
        Partial Private Sub OnNextBatchValueChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
        Partial Private Sub OnNextBatchValueChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property WaitToUpdate in the schema.
        '''</summary>
        Public Property WaitToUpdate() As String
            Get
                Return Me._WaitToUpdate
            End Get
            Set
                Me.OnWaitToUpdateChanging(value)
                Me._WaitToUpdate = value
                Me.OnWaitToUpdateChanged
            End Set
        End Property
        Private _WaitToUpdate As String
        Partial Private Sub OnWaitToUpdateChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnWaitToUpdateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Wrksrctbl in the schema.
        '''</summary>
        Public Property Wrksrctbl() As Wrksrctbl
            Get
                Return Me._Wrksrctbl
            End Get
            Set
                Me._Wrksrctbl = value
            End Set
        End Property
        Private _Wrksrctbl As Wrksrctbl
    End Class
    '''<summary>
    '''There are no comments for ilockboxModel.DetailTbl in the schema.
    '''</summary>
    '''<KeyProperties>
    '''SiteId
    '''ProcessDt
    '''WorkSource
    '''SubSet
    '''BatchNumber
    '''TranNo
    '''SeqNo
    '''SubSeqNo
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("SiteId", "ProcessDt", "WorkSource", "SubSet", "BatchNumber", "TranNo", "SeqNo", "SubSeqNo")>  _
    Partial Public Class DetailTbl
        '''<summary>
        '''Create a new DetailTbl object.
        '''</summary>
        '''<param name="siteId">Initial value of SiteId.</param>
        '''<param name="processDt">Initial value of ProcessDt.</param>
        '''<param name="workSource">Initial value of WorkSource.</param>
        '''<param name="subSet">Initial value of SubSet.</param>
        '''<param name="batchNumber">Initial value of BatchNumber.</param>
        '''<param name="tranNo">Initial value of TranNo.</param>
        '''<param name="seqNo">Initial value of SeqNo.</param>
        '''<param name="subSeqNo">Initial value of SubSeqNo.</param>
        '''<param name="itemType">Initial value of ItemType.</param>
        '''<param name="batchType">Initial value of BatchType.</param>
        Public Shared Function CreateDetailTbl(ByVal siteId As Short, ByVal processDt As Date, ByVal workSource As String, ByVal subSet As Short, ByVal batchNumber As String, ByVal tranNo As Integer, ByVal seqNo As Integer, ByVal subSeqNo As Integer, ByVal itemType As String, ByVal batchType As Short) As DetailTbl
            Dim detailTbl As DetailTbl = New DetailTbl()
            detailTbl.SiteId = siteId
            detailTbl.ProcessDt = processDt
            detailTbl.WorkSource = workSource
            detailTbl.SubSet = subSet
            detailTbl.BatchNumber = batchNumber
            detailTbl.TranNo = tranNo
            detailTbl.SeqNo = seqNo
            detailTbl.SubSeqNo = subSeqNo
            detailTbl.ItemType = itemType
            detailTbl.BatchType = batchType
            Return detailTbl
        End Function
        '''<summary>
        '''There are no comments for Property SiteId in the schema.
        '''</summary>
        Public Property SiteId() As Short
            Get
                Return Me._SiteId
            End Get
            Set
                Me.OnSiteIdChanging(value)
                Me._SiteId = value
                Me.OnSiteIdChanged
            End Set
        End Property
        Private _SiteId As Short
        Partial Private Sub OnSiteIdChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnSiteIdChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ProcessDt in the schema.
        '''</summary>
        Public Property ProcessDt() As Date
            Get
                Return Me._ProcessDt
            End Get
            Set
                Me.OnProcessDtChanging(value)
                Me._ProcessDt = value
                Me.OnProcessDtChanged
            End Set
        End Property
        Private _ProcessDt As Date
        Partial Private Sub OnProcessDtChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnProcessDtChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property WorkSource in the schema.
        '''</summary>
        Public Property WorkSource() As String
            Get
                Return Me._WorkSource
            End Get
            Set
                Me.OnWorkSourceChanging(value)
                Me._WorkSource = value
                Me.OnWorkSourceChanged
            End Set
        End Property
        Private _WorkSource As String
        Partial Private Sub OnWorkSourceChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnWorkSourceChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SubSet in the schema.
        '''</summary>
        Public Property SubSet() As Short
            Get
                Return Me._SubSet
            End Get
            Set
                Me.OnSubSetChanging(value)
                Me._SubSet = value
                Me.OnSubSetChanged
            End Set
        End Property
        Private _SubSet As Short
        Partial Private Sub OnSubSetChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnSubSetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BatchNumber in the schema.
        '''</summary>
        Public Property BatchNumber() As String
            Get
                Return Me._BatchNumber
            End Get
            Set
                Me.OnBatchNumberChanging(value)
                Me._BatchNumber = value
                Me.OnBatchNumberChanged
            End Set
        End Property
        Private _BatchNumber As String
        Partial Private Sub OnBatchNumberChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnBatchNumberChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property TranNo in the schema.
        '''</summary>
        Public Property TranNo() As Integer
            Get
                Return Me._TranNo
            End Get
            Set
                Me.OnTranNoChanging(value)
                Me._TranNo = value
                Me.OnTranNoChanged
            End Set
        End Property
        Private _TranNo As Integer
        Partial Private Sub OnTranNoChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnTranNoChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SeqNo in the schema.
        '''</summary>
        Public Property SeqNo() As Integer
            Get
                Return Me._SeqNo
            End Get
            Set
                Me.OnSeqNoChanging(value)
                Me._SeqNo = value
                Me.OnSeqNoChanged
            End Set
        End Property
        Private _SeqNo As Integer
        Partial Private Sub OnSeqNoChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnSeqNoChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SubSeqNo in the schema.
        '''</summary>
        Public Property SubSeqNo() As Integer
            Get
                Return Me._SubSeqNo
            End Get
            Set
                Me.OnSubSeqNoChanging(value)
                Me._SubSeqNo = value
                Me.OnSubSeqNoChanged
            End Set
        End Property
        Private _SubSeqNo As Integer
        Partial Private Sub OnSubSeqNoChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnSubSeqNoChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property P1ImgSeqNo in the schema.
        '''</summary>
        Public Property P1ImgSeqNo() As Global.System.Nullable(Of Integer)
            Get
                Return Me._P1ImgSeqNo
            End Get
            Set
                Me.OnP1ImgSeqNoChanging(value)
                Me._P1ImgSeqNo = value
                Me.OnP1ImgSeqNoChanged
            End Set
        End Property
        Private _P1ImgSeqNo As Global.System.Nullable(Of Integer)
        Partial Private Sub OnP1ImgSeqNoChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnP1ImgSeqNoChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property P2ImgSeqNo in the schema.
        '''</summary>
        Public Property P2ImgSeqNo() As Global.System.Nullable(Of Integer)
            Get
                Return Me._P2ImgSeqNo
            End Get
            Set
                Me.OnP2ImgSeqNoChanging(value)
                Me._P2ImgSeqNo = value
                Me.OnP2ImgSeqNoChanged
            End Set
        End Property
        Private _P2ImgSeqNo As Global.System.Nullable(Of Integer)
        Partial Private Sub OnP2ImgSeqNoChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnP2ImgSeqNoChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ItemType in the schema.
        '''</summary>
        Public Property ItemType() As String
            Get
                Return Me._ItemType
            End Get
            Set
                Me.OnItemTypeChanging(value)
                Me._ItemType = value
                Me.OnItemTypeChanged
            End Set
        End Property
        Private _ItemType As String
        Partial Private Sub OnItemTypeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnItemTypeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BatchType in the schema.
        '''</summary>
        Public Property BatchType() As Short
            Get
                Return Me._BatchType
            End Get
            Set
                Me.OnBatchTypeChanging(value)
                Me._BatchType = value
                Me.OnBatchTypeChanged
            End Set
        End Property
        Private _BatchType As Short
        Partial Private Sub OnBatchTypeChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnBatchTypeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property UserFlag1 in the schema.
        '''</summary>
        Public Property UserFlag1() As String
            Get
                Return Me._UserFlag1
            End Get
            Set
                Me.OnUserFlag1Changing(value)
                Me._UserFlag1 = value
                Me.OnUserFlag1Changed
            End Set
        End Property
        Private _UserFlag1 As String
        Partial Private Sub OnUserFlag1Changing(ByVal value As String)
        End Sub
        Partial Private Sub OnUserFlag1Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property UserFlag2 in the schema.
        '''</summary>
        Public Property UserFlag2() As String
            Get
                Return Me._UserFlag2
            End Get
            Set
                Me.OnUserFlag2Changing(value)
                Me._UserFlag2 = value
                Me.OnUserFlag2Changed
            End Set
        End Property
        Private _UserFlag2 As String
        Partial Private Sub OnUserFlag2Changing(ByVal value As String)
        End Sub
        Partial Private Sub OnUserFlag2Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property UserFlag3 in the schema.
        '''</summary>
        Public Property UserFlag3() As String
            Get
                Return Me._UserFlag3
            End Get
            Set
                Me.OnUserFlag3Changing(value)
                Me._UserFlag3 = value
                Me.OnUserFlag3Changed
            End Set
        End Property
        Private _UserFlag3 As String
        Partial Private Sub OnUserFlag3Changing(ByVal value As String)
        End Sub
        Partial Private Sub OnUserFlag3Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property UserFlag4 in the schema.
        '''</summary>
        Public Property UserFlag4() As String
            Get
                Return Me._UserFlag4
            End Get
            Set
                Me.OnUserFlag4Changing(value)
                Me._UserFlag4 = value
                Me.OnUserFlag4Changed
            End Set
        End Property
        Private _UserFlag4 As String
        Partial Private Sub OnUserFlag4Changing(ByVal value As String)
        End Sub
        Partial Private Sub OnUserFlag4Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property UserInt1 in the schema.
        '''</summary>
        Public Property UserInt1() As Global.System.Nullable(Of Integer)
            Get
                Return Me._UserInt1
            End Get
            Set
                Me.OnUserInt1Changing(value)
                Me._UserInt1 = value
                Me.OnUserInt1Changed
            End Set
        End Property
        Private _UserInt1 As Global.System.Nullable(Of Integer)
        Partial Private Sub OnUserInt1Changing(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnUserInt1Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property UserInt2 in the schema.
        '''</summary>
        Public Property UserInt2() As Global.System.Nullable(Of Integer)
            Get
                Return Me._UserInt2
            End Get
            Set
                Me.OnUserInt2Changing(value)
                Me._UserInt2 = value
                Me.OnUserInt2Changed
            End Set
        End Property
        Private _UserInt2 As Global.System.Nullable(Of Integer)
        Partial Private Sub OnUserInt2Changing(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnUserInt2Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property UserInt3 in the schema.
        '''</summary>
        Public Property UserInt3() As Global.System.Nullable(Of Integer)
            Get
                Return Me._UserInt3
            End Get
            Set
                Me.OnUserInt3Changing(value)
                Me._UserInt3 = value
                Me.OnUserInt3Changed
            End Set
        End Property
        Private _UserInt3 As Global.System.Nullable(Of Integer)
        Partial Private Sub OnUserInt3Changing(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnUserInt3Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property UserString1 in the schema.
        '''</summary>
        Public Property UserString1() As String
            Get
                Return Me._UserString1
            End Get
            Set
                Me.OnUserString1Changing(value)
                Me._UserString1 = value
                Me.OnUserString1Changed
            End Set
        End Property
        Private _UserString1 As String
        Partial Private Sub OnUserString1Changing(ByVal value As String)
        End Sub
        Partial Private Sub OnUserString1Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property UserString2 in the schema.
        '''</summary>
        Public Property UserString2() As String
            Get
                Return Me._UserString2
            End Get
            Set
                Me.OnUserString2Changing(value)
                Me._UserString2 = value
                Me.OnUserString2Changed
            End Set
        End Property
        Private _UserString2 As String
        Partial Private Sub OnUserString2Changing(ByVal value As String)
        End Sub
        Partial Private Sub OnUserString2Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property UserString3 in the schema.
        '''</summary>
        Public Property UserString3() As String
            Get
                Return Me._UserString3
            End Get
            Set
                Me.OnUserString3Changing(value)
                Me._UserString3 = value
                Me.OnUserString3Changed
            End Set
        End Property
        Private _UserString3 As String
        Partial Private Sub OnUserString3Changing(ByVal value As String)
        End Sub
        Partial Private Sub OnUserString3Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property SubType in the schema.
        '''</summary>
        Public Property SubType() As String
            Get
                Return Me._SubType
            End Get
            Set
                Me.OnSubTypeChanging(value)
                Me._SubType = value
                Me.OnSubTypeChanged
            End Set
        End Property
        Private _SubType As String
        Partial Private Sub OnSubTypeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnSubTypeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property UserFlag5 in the schema.
        '''</summary>
        Public Property UserFlag5() As String
            Get
                Return Me._UserFlag5
            End Get
            Set
                Me.OnUserFlag5Changing(value)
                Me._UserFlag5 = value
                Me.OnUserFlag5Changed
            End Set
        End Property
        Private _UserFlag5 As String
        Partial Private Sub OnUserFlag5Changing(ByVal value As String)
        End Sub
        Partial Private Sub OnUserFlag5Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property UserFlag6 in the schema.
        '''</summary>
        Public Property UserFlag6() As String
            Get
                Return Me._UserFlag6
            End Get
            Set
                Me.OnUserFlag6Changing(value)
                Me._UserFlag6 = value
                Me.OnUserFlag6Changed
            End Set
        End Property
        Private _UserFlag6 As String
        Partial Private Sub OnUserFlag6Changing(ByVal value As String)
        End Sub
        Partial Private Sub OnUserFlag6Changed()
        End Sub
        '''<summary>
        '''There are no comments for Batchtbl in the schema.
        '''</summary>
        Public Property Batchtbl() As Batchtbl
            Get
                Return Me._Batchtbl
            End Get
            Set
                Me._Batchtbl = value
            End Set
        End Property
        Private _Batchtbl As Batchtbl
    End Class
    '''<summary>
    '''There are no comments for ilockboxModel.ImgTbl in the schema.
    '''</summary>
    '''<KeyProperties>
    '''WorkSource
    '''SubSet
    '''BatchMode
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("WorkSource", "SubSet", "BatchMode")>  _
    Partial Public Class ImgTbl
        '''<summary>
        '''Create a new ImgTbl object.
        '''</summary>
        '''<param name="workSource">Initial value of WorkSource.</param>
        '''<param name="subSet">Initial value of SubSet.</param>
        '''<param name="batchMode">Initial value of BatchMode.</param>
        '''<param name="imageDisp">Initial value of ImageDisp.</param>
        '''<param name="imagePost">Initial value of ImagePost.</param>
        Public Shared Function CreateImgTbl(ByVal workSource As String, ByVal subSet As Short, ByVal batchMode As Short, ByVal imageDisp As String, ByVal imagePost As String) As ImgTbl
            Dim imgTbl As ImgTbl = New ImgTbl()
            imgTbl.WorkSource = workSource
            imgTbl.SubSet = subSet
            imgTbl.BatchMode = batchMode
            imgTbl.ImageDisp = imageDisp
            imgTbl.ImagePost = imagePost
            Return imgTbl
        End Function
        '''<summary>
        '''There are no comments for Property WorkSource in the schema.
        '''</summary>
        Public Property WorkSource() As String
            Get
                Return Me._WorkSource
            End Get
            Set
                Me.OnWorkSourceChanging(value)
                Me._WorkSource = value
                Me.OnWorkSourceChanged
            End Set
        End Property
        Private _WorkSource As String
        Partial Private Sub OnWorkSourceChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnWorkSourceChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SubSet in the schema.
        '''</summary>
        Public Property SubSet() As Short
            Get
                Return Me._SubSet
            End Get
            Set
                Me.OnSubSetChanging(value)
                Me._SubSet = value
                Me.OnSubSetChanged
            End Set
        End Property
        Private _SubSet As Short
        Partial Private Sub OnSubSetChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnSubSetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BatchMode in the schema.
        '''</summary>
        Public Property BatchMode() As Short
            Get
                Return Me._BatchMode
            End Get
            Set
                Me.OnBatchModeChanging(value)
                Me._BatchMode = value
                Me.OnBatchModeChanged
            End Set
        End Property
        Private _BatchMode As Short
        Partial Private Sub OnBatchModeChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnBatchModeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ImageDisp in the schema.
        '''</summary>
        Public Property ImageDisp() As String
            Get
                Return Me._ImageDisp
            End Get
            Set
                Me.OnImageDispChanging(value)
                Me._ImageDisp = value
                Me.OnImageDispChanged
            End Set
        End Property
        Private _ImageDisp As String
        Partial Private Sub OnImageDispChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnImageDispChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ImagePost in the schema.
        '''</summary>
        Public Property ImagePost() As String
            Get
                Return Me._ImagePost
            End Get
            Set
                Me.OnImagePostChanging(value)
                Me._ImagePost = value
                Me.OnImagePostChanged
            End Set
        End Property
        Private _ImagePost As String
        Partial Private Sub OnImagePostChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnImagePostChanged()
        End Sub
        '''<summary>
        '''There are no comments for Wrksrctbl in the schema.
        '''</summary>
        Public Property Wrksrctbl() As Wrksrctbl
            Get
                Return Me._Wrksrctbl
            End Get
            Set
                Me._Wrksrctbl = value
            End Set
        End Property
        Private _Wrksrctbl As Wrksrctbl
    End Class
    '''<summary>
    '''There are no comments for ilockboxModel.ItemSelectTbl in the schema.
    '''</summary>
    '''<KeyProperties>
    '''WorkSource
    '''SubSet
    '''BatchMode
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("WorkSource", "SubSet", "BatchMode")>  _
    Partial Public Class ItemSelectTbl
        '''<summary>
        '''Create a new ItemSelectTbl object.
        '''</summary>
        '''<param name="workSource">Initial value of WorkSource.</param>
        '''<param name="subSet">Initial value of SubSet.</param>
        '''<param name="batchMode">Initial value of BatchMode.</param>
        '''<param name="itemDisp">Initial value of ItemDisp.</param>
        '''<param name="itemPost">Initial value of ItemPost.</param>
        Public Shared Function CreateItemSelectTbl(ByVal workSource As String, ByVal subSet As Short, ByVal batchMode As Short, ByVal itemDisp As String, ByVal itemPost As String) As ItemSelectTbl
            Dim itemSelectTbl As ItemSelectTbl = New ItemSelectTbl()
            itemSelectTbl.WorkSource = workSource
            itemSelectTbl.SubSet = subSet
            itemSelectTbl.BatchMode = batchMode
            itemSelectTbl.ItemDisp = itemDisp
            itemSelectTbl.ItemPost = itemPost
            Return itemSelectTbl
        End Function
        '''<summary>
        '''There are no comments for Property WorkSource in the schema.
        '''</summary>
        Public Property WorkSource() As String
            Get
                Return Me._WorkSource
            End Get
            Set
                Me.OnWorkSourceChanging(value)
                Me._WorkSource = value
                Me.OnWorkSourceChanged
            End Set
        End Property
        Private _WorkSource As String
        Partial Private Sub OnWorkSourceChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnWorkSourceChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SubSet in the schema.
        '''</summary>
        Public Property SubSet() As Short
            Get
                Return Me._SubSet
            End Get
            Set
                Me.OnSubSetChanging(value)
                Me._SubSet = value
                Me.OnSubSetChanged
            End Set
        End Property
        Private _SubSet As Short
        Partial Private Sub OnSubSetChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnSubSetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BatchMode in the schema.
        '''</summary>
        Public Property BatchMode() As Short
            Get
                Return Me._BatchMode
            End Get
            Set
                Me.OnBatchModeChanging(value)
                Me._BatchMode = value
                Me.OnBatchModeChanged
            End Set
        End Property
        Private _BatchMode As Short
        Partial Private Sub OnBatchModeChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnBatchModeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ItemDisp in the schema.
        '''</summary>
        Public Property ItemDisp() As String
            Get
                Return Me._ItemDisp
            End Get
            Set
                Me.OnItemDispChanging(value)
                Me._ItemDisp = value
                Me.OnItemDispChanged
            End Set
        End Property
        Private _ItemDisp As String
        Partial Private Sub OnItemDispChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnItemDispChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ItemPost in the schema.
        '''</summary>
        Public Property ItemPost() As String
            Get
                Return Me._ItemPost
            End Get
            Set
                Me.OnItemPostChanging(value)
                Me._ItemPost = value
                Me.OnItemPostChanged
            End Set
        End Property
        Private _ItemPost As String
        Partial Private Sub OnItemPostChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnItemPostChanged()
        End Sub
        '''<summary>
        '''There are no comments for Wrksrctbl in the schema.
        '''</summary>
        Public Property Wrksrctbl() As Wrksrctbl
            Get
                Return Me._Wrksrctbl
            End Get
            Set
                Me._Wrksrctbl = value
            End Set
        End Property
        Private _Wrksrctbl As Wrksrctbl
    End Class
    '''<summary>
    '''There are no comments for ilockboxModel.RegionCodes in the schema.
    '''</summary>
    '''<KeyProperties>
    '''Region
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("Region")>  _
    Partial Public Class RegionCodes
        '''<summary>
        '''Create a new RegionCodes object.
        '''</summary>
        '''<param name="region">Initial value of Region.</param>
        '''<param name="regionName">Initial value of RegionName.</param>
        '''<param name="addr1">Initial value of Addr1.</param>
        '''<param name="city">Initial value of City.</param>
        '''<param name="state">Initial value of State.</param>
        '''<param name="zipCode">Initial value of ZipCode.</param>
        Public Shared Function CreateRegionCodes(ByVal region As String, ByVal regionName As String, ByVal addr1 As String, ByVal city As String, ByVal state As String, ByVal zipCode As String) As RegionCodes
            Dim regionCodes As RegionCodes = New RegionCodes()
            regionCodes.Region = region
            regionCodes.RegionName = regionName
            regionCodes.Addr1 = addr1
            regionCodes.City = city
            regionCodes.State = state
            regionCodes.ZipCode = zipCode
            Return regionCodes
        End Function
        '''<summary>
        '''There are no comments for Property Region in the schema.
        '''</summary>
        Public Property Region() As String
            Get
                Return Me._Region
            End Get
            Set
                Me.OnRegionChanging(value)
                Me._Region = value
                Me.OnRegionChanged
            End Set
        End Property
        Private _Region As String
        Partial Private Sub OnRegionChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnRegionChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property RegionName in the schema.
        '''</summary>
        Public Property RegionName() As String
            Get
                Return Me._RegionName
            End Get
            Set
                Me.OnRegionNameChanging(value)
                Me._RegionName = value
                Me.OnRegionNameChanged
            End Set
        End Property
        Private _RegionName As String
        Partial Private Sub OnRegionNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnRegionNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property StreetNumber in the schema.
        '''</summary>
        Public Property StreetNumber() As String
            Get
                Return Me._StreetNumber
            End Get
            Set
                Me.OnStreetNumberChanging(value)
                Me._StreetNumber = value
                Me.OnStreetNumberChanged
            End Set
        End Property
        Private _StreetNumber As String
        Partial Private Sub OnStreetNumberChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnStreetNumberChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Addr1 in the schema.
        '''</summary>
        Public Property Addr1() As String
            Get
                Return Me._Addr1
            End Get
            Set
                Me.OnAddr1Changing(value)
                Me._Addr1 = value
                Me.OnAddr1Changed
            End Set
        End Property
        Private _Addr1 As String
        Partial Private Sub OnAddr1Changing(ByVal value As String)
        End Sub
        Partial Private Sub OnAddr1Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property City in the schema.
        '''</summary>
        Public Property City() As String
            Get
                Return Me._City
            End Get
            Set
                Me.OnCityChanging(value)
                Me._City = value
                Me.OnCityChanged
            End Set
        End Property
        Private _City As String
        Partial Private Sub OnCityChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCityChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property State in the schema.
        '''</summary>
        Public Property State() As String
            Get
                Return Me._State
            End Get
            Set
                Me.OnStateChanging(value)
                Me._State = value
                Me.OnStateChanged
            End Set
        End Property
        Private _State As String
        Partial Private Sub OnStateChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnStateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ZipCode in the schema.
        '''</summary>
        Public Property ZipCode() As String
            Get
                Return Me._ZipCode
            End Get
            Set
                Me.OnZipCodeChanging(value)
                Me._ZipCode = value
                Me.OnZipCodeChanged
            End Set
        End Property
        Private _ZipCode As String
        Partial Private Sub OnZipCodeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnZipCodeChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for ilockboxModel.Wrksrctbl in the schema.
    '''</summary>
    '''<KeyProperties>
    '''WorkSource
    '''SubSet
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("WorkSource", "SubSet")>  _
    Partial Public Class Wrksrctbl
        '''<summary>
        '''Create a new Wrksrctbl object.
        '''</summary>
        '''<param name="workSource">Initial value of WorkSource.</param>
        '''<param name="subSet">Initial value of SubSet.</param>
        '''<param name="name">Initial value of Name.</param>
        '''<param name="imagePath">Initial value of ImagePath.</param>
        '''<param name="xmlPath">Initial value of XmlPath.</param>
        '''<param name="autoTrans">Initial value of AutoTrans.</param>
        '''<param name="belongsToGroup">Initial value of BelongsToGroup.</param>
        '''<param name="siteID">Initial value of SiteID.</param>
        '''<param name="isItActive">Initial value of IsItActive.</param>
        Public Shared Function CreateWrksrctbl(ByVal workSource As String, ByVal subSet As Short, ByVal name As String, ByVal imagePath As String, ByVal xmlPath As String, ByVal autoTrans As String, ByVal belongsToGroup As String, ByVal siteID As Short, ByVal isItActive As String) As Wrksrctbl
            Dim wrksrctbl As Wrksrctbl = New Wrksrctbl()
            wrksrctbl.WorkSource = workSource
            wrksrctbl.SubSet = subSet
            wrksrctbl.Name = name
            wrksrctbl.ImagePath = imagePath
            wrksrctbl.XmlPath = xmlPath
            wrksrctbl.AutoTrans = autoTrans
            wrksrctbl.BelongsToGroup = belongsToGroup
            wrksrctbl.SiteID = siteID
            wrksrctbl.IsItActive = isItActive
            Return wrksrctbl
        End Function
        '''<summary>
        '''There are no comments for Property WorkSource in the schema.
        '''</summary>
        Public Property WorkSource() As String
            Get
                Return Me._WorkSource
            End Get
            Set
                Me.OnWorkSourceChanging(value)
                Me._WorkSource = value
                Me.OnWorkSourceChanged
            End Set
        End Property
        Private _WorkSource As String
        Partial Private Sub OnWorkSourceChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnWorkSourceChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SubSet in the schema.
        '''</summary>
        Public Property SubSet() As Short
            Get
                Return Me._SubSet
            End Get
            Set
                Me.OnSubSetChanging(value)
                Me._SubSet = value
                Me.OnSubSetChanged
            End Set
        End Property
        Private _SubSet As Short
        Partial Private Sub OnSubSetChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnSubSetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
            End Set
        End Property
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ImagePath in the schema.
        '''</summary>
        Public Property ImagePath() As String
            Get
                Return Me._ImagePath
            End Get
            Set
                Me.OnImagePathChanging(value)
                Me._ImagePath = value
                Me.OnImagePathChanged
            End Set
        End Property
        Private _ImagePath As String
        Partial Private Sub OnImagePathChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnImagePathChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property XmlPath in the schema.
        '''</summary>
        Public Property XmlPath() As String
            Get
                Return Me._XmlPath
            End Get
            Set
                Me.OnXmlPathChanging(value)
                Me._XmlPath = value
                Me.OnXmlPathChanged
            End Set
        End Property
        Private _XmlPath As String
        Partial Private Sub OnXmlPathChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnXmlPathChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property AutoTrans in the schema.
        '''</summary>
        Public Property AutoTrans() As String
            Get
                Return Me._AutoTrans
            End Get
            Set
                Me.OnAutoTransChanging(value)
                Me._AutoTrans = value
                Me.OnAutoTransChanged
            End Set
        End Property
        Private _AutoTrans As String
        Partial Private Sub OnAutoTransChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnAutoTransChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BelongsToGroup in the schema.
        '''</summary>
        Public Property BelongsToGroup() As String
            Get
                Return Me._BelongsToGroup
            End Get
            Set
                Me.OnBelongsToGroupChanging(value)
                Me._BelongsToGroup = value
                Me.OnBelongsToGroupChanged
            End Set
        End Property
        Private _BelongsToGroup As String
        Partial Private Sub OnBelongsToGroupChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnBelongsToGroupChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property XmlImagePath in the schema.
        '''</summary>
        Public Property XmlImagePath() As String
            Get
                Return Me._XmlImagePath
            End Get
            Set
                Me.OnXmlImagePathChanging(value)
                Me._XmlImagePath = value
                Me.OnXmlImagePathChanged
            End Set
        End Property
        Private _XmlImagePath As String
        Partial Private Sub OnXmlImagePathChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnXmlImagePathChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SiteID in the schema.
        '''</summary>
        Public Property SiteID() As Short
            Get
                Return Me._SiteID
            End Get
            Set
                Me.OnSiteIDChanging(value)
                Me._SiteID = value
                Me.OnSiteIDChanged
            End Set
        End Property
        Private _SiteID As Short
        Partial Private Sub OnSiteIDChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnSiteIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ItemFilter in the schema.
        '''</summary>
        Public Property ItemFilter() As String
            Get
                Return Me._ItemFilter
            End Get
            Set
                Me.OnItemFilterChanging(value)
                Me._ItemFilter = value
                Me.OnItemFilterChanged
            End Set
        End Property
        Private _ItemFilter As String
        Partial Private Sub OnItemFilterChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnItemFilterChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property IsItActive in the schema.
        '''</summary>
        Public Property IsItActive() As String
            Get
                Return Me._IsItActive
            End Get
            Set
                Me.OnIsItActiveChanging(value)
                Me._IsItActive = value
                Me.OnIsItActiveChanged
            End Set
        End Property
        Private _IsItActive As String
        Partial Private Sub OnIsItActiveChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnIsItActiveChanged()
        End Sub
        '''<summary>
        '''There are no comments for Batchmodetbl in the schema.
        '''</summary>
        Public Property Batchmodetbl() As Global.System.Collections.ObjectModel.Collection(Of Batchmodetbl)
            Get
                Return Me._Batchmodetbl
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    Me._Batchmodetbl = value
                End If
            End Set
        End Property
        Private _Batchmodetbl As Global.System.Collections.ObjectModel.Collection(Of Batchmodetbl) = New Global.System.Collections.ObjectModel.Collection(Of Batchmodetbl)()
        '''<summary>
        '''There are no comments for Batchtbl in the schema.
        '''</summary>
        Public Property Batchtbl() As Global.System.Collections.ObjectModel.Collection(Of Batchtbl)
            Get
                Return Me._Batchtbl
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    Me._Batchtbl = value
                End If
            End Set
        End Property
        Private _Batchtbl As Global.System.Collections.ObjectModel.Collection(Of Batchtbl) = New Global.System.Collections.ObjectModel.Collection(Of Batchtbl)()
        '''<summary>
        '''There are no comments for BatchValue in the schema.
        '''</summary>
        Public Property BatchValue() As Global.System.Collections.ObjectModel.Collection(Of BatchValue)
            Get
                Return Me._BatchValue
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    Me._BatchValue = value
                End If
            End Set
        End Property
        Private _BatchValue As Global.System.Collections.ObjectModel.Collection(Of BatchValue) = New Global.System.Collections.ObjectModel.Collection(Of BatchValue)()
        '''<summary>
        '''There are no comments for ImgTbl in the schema.
        '''</summary>
        Public Property ImgTbl() As Global.System.Collections.ObjectModel.Collection(Of ImgTbl)
            Get
                Return Me._ImgTbl
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    Me._ImgTbl = value
                End If
            End Set
        End Property
        Private _ImgTbl As Global.System.Collections.ObjectModel.Collection(Of ImgTbl) = New Global.System.Collections.ObjectModel.Collection(Of ImgTbl)()
        '''<summary>
        '''There are no comments for ItemSelectTbl in the schema.
        '''</summary>
        Public Property ItemSelectTbl() As Global.System.Collections.ObjectModel.Collection(Of ItemSelectTbl)
            Get
                Return Me._ItemSelectTbl
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    Me._ItemSelectTbl = value
                End If
            End Set
        End Property
        Private _ItemSelectTbl As Global.System.Collections.ObjectModel.Collection(Of ItemSelectTbl) = New Global.System.Collections.ObjectModel.Collection(Of ItemSelectTbl)()
    End Class
End Namespace
